import AutoProof.Basic
import AutoProof.Definitions.Group
import AutoProof.Lemmas.CancellationLaw
import AutoProof.Theorems.UniqueIdentity
import AutoProof.Theorems.UniqueInverse
import AutoProof.Examples.DirectProofExample
import AutoProof.Examples.ContradictionExample
